### ISSUE TITLE
i want to talk about ekonsulat i can pay for program 

### ISSUE THREAD

**Issue by jayz0094** [olecom/plwiza.user.js#2]
my email is pjay0094@gmail.com

**Comment by olecom** [comment]
@jayz0094, hi! I think this is occupied by known people to automate the process in different, say corrupted way.

This work was just to make it easy to fill the forms. COPY/PASTE instead of long and error prone input.

**Comment by olecom** [comment]
https://en.wikipedia.org/wiki/Polish_cash-for-visa_scandal
